<a href="https://colab.research.google.com/github/Tanvi-diwakar/data-science/blob/main/Day_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. in-built function
2. user defined..........

:pip----> python install package -----> allows python to install different setups

In [1]:
!pip install numpy

In [2]:
import numpy as np

In [3]:
array_1d = np.array ([1,2,3,4,5,6])
print("this is a 1d array\n", array_1d)

this is a 1d array
 [1 2 3 4 5 6]


In [4]:
array_2d = np.array([[1,2,3], [4,5,6]])
print("this is 2d array\n", array_2d)

this is 2d array
 [[1 2 3]
 [4 5 6]]


In [5]:
range_array = np.arange(1, 20, 2)
print(range_array)

[ 1  3  5  7  9 11 13 15 17 19]


In [6]:
#check the shape
print(array_2d.shape) # it will return walue in row and column

(2, 3)


In [7]:
print(array_2d.size)

6


In [8]:
print(array_2d.ndim) # type of array

2


In [9]:
reshaped_array = np.reshape(array_2d, (3, 2))
print (reshaped_array)

[[1 2]
 [3 4]
 [5 6]]


In [10]:
new_array = range_array + 10
print(new_array)

[11 13 15 17 19 21 23 25 27 29]


In [11]:
array2d_add = np.array([[1,2,3,4], [5,6,7,8]])
print(array2d_add + 10)

[[11 12 13 14]
 [15 16 17 18]]
